jwt:
  secret: mysupercomplexsecret
server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita
    password: root
    username: root
  sql:
    init:
      mode: never
